web-slate/java-basics

.github/PULL_REQUEST_TEMPLATE.md, .tours/10-interesting-things-in-strings-to-remember.tour, .vscode/settings.json, OOPS/README.md, __complexities/big-o-notations.md, data_structures/README.md, data_types/README.md
=> tech: base structure

data_types/BasicDataType.java, data_types/primitive_datatype/FloatTypes.java, data_types/primitive_datatype/IntegerTypes.java
1. Update primitive datatype with integer and float
=> docs: add integer and float datatypes

data_types/README.md, data_types/index.md
1. added data type classification docs
=> docs(data_types): update detailed data type classification

README.md, data_types/String/index.md, leet_code/index.md, leet_code/palindrome/QuickSolution.java, leet_code/palindrome/tests/QuickSolutionTest.java, pom.xml
1. add leet code with test case
=> tech(base): add leet code with test case

data_types/BasicDataType.java, data_types/index.md
1. Added some errors and info about datatypes
=> docs:added some notes about datatypes

basics/Operators/index.md
=> docs:add operators

basics/Operators/index.md, data_types/String/Strings.java, data_types/String/index.md
1. Added String methods and examples
=> docs:add strings

basics/Operators/Arithmetic.java, basics/Operators/Assignment.java, basics/Operators/Comparision.java, basics/Operators/index.md, data_types/String/Strings.java, data_types/String/index.md
1. Added Arithmetic operator
1. Added Assignment operator
2. Added Comparision operator
=> docs:added examples of operators

basics/intro.md, basics/statements/Else_if.java, basics/statements/if.java, basics/statements/if_else.java, data_types/math/Math.java
=> docs:added conditional statements

.github/workflows/docs.yml
=> tech: update workflow

src/main/java/basics/Operators/index.md, src/main/java/basics/statements/conditional/elseif_example.java, src/main/java/basics/statements/conditional/if_example.java, src/main/java/basics/statements/conditional/ifelse_example.java, src/main/java/basics/statements/loop/for_examples.java, src/main/java/basics/statements/loop/while_examples.java, target/classes/basics/Operators/index.md
1. added while loop
1. created conditional statement
=> docs:added while loop

src/main/java/algorithms/math/EuclideanFindDistance.java, src/main/java/basics/introduction.md
=> algorithm: add euclidean example

target/classes/basics/introduction.md
1.Created collections_framework and advanced folders
=> create: base docs collections_framework and advanced

src/main/java/data_structures/introduction.md, target/classes/data_structures/introduction.md
1.  created docs for datastructure
=> docs: created docs for datastructure

.github/workflows/docs.yml, generate_docs.sh, src/main/java/basics/introduction.md, src/main/java/data_types/introduction.md, target/classes/basics/introduction.md, target/classes/data_types/introduction.md
1. tech: update script
2. tech: update docs
=> tech: update script and docs

.github/workflows/docs.yml, generate_docs.sh
=> fix: update script

src/main/java/basics/introduction.md, target/classes/basics/introduction.md
=> docs: update basics introduction

src/main/java/data_structures/array/introduction.md, target/classes/data_structures/array/introduction.md
1. Add Fixed and Dynamic Arrays
2. What is amortized
=> data_structure: add array basics docs

src/main/java/basics/control_flow/IfElseExamples.java, src/main/java/collections_framework/array_list/ArrayListExamples.java, src/main/java/collections_framework/array_list/introduction.md, target/classes/collections_framework/array_list/introduction.md
=> collection/array_list: create docs for arraylist

src/main/java/leet_code/move_zeroes/MoveZeroesProblem.java, src/main/java/leet_code/palindrome/QuickSolution.java
1. Added Move Zeroes Problem
1. Three Better Solutions
=> leet_code: array move zeroes problem

.github/workflows/docs.yml, generate_docs.sh, src/main/java/data_types/non_primitive_data_type/fixed_array/FixedArrayExample.java, src/main/java/data_types/non_primitive_data_type/introduction.md, src/main/java/leet_code/move_zeroes/MoveZeroesProblem.java, target/classes/data_types/non_primitive_data_type/introduction.md
1. updated move zeroes problem
2. update script and docs workflow
=> data_types: add fixed array examples with byte and int

src/main/java/basics/control_flow/loop/BasicLoopProblems.md
1. Added 5 basic qns and solutions in loop
=> docs: added some loop examples

src/main/java/basics/fast_track.md, target/surefire-reports/TEST-leet_code.palindrome.tests.QuickSolutionTest.xml, target/surefire-reports/leet_code.palindrome.tests.QuickSolutionTest.txt
=> basics: add fast track doc

src/main/java/basics/fast_track.md, target/surefire-reports/TEST-leet_code.palindrome.tests.QuickSolutionTest.xml, target/surefire-reports/leet_code.palindrome.tests.QuickSolutionTest.txt
1. update the heading for all sections
=> fix: update the heading for all sections

src/main/java/leet_code/two_sum/TwoSumProblem.java
1.Added bruteforce,suboptimal and optimal approach
=> docs: added three approaches to two sum problem

src/main/java/leet_code/string/easy/valid_palindrome/ValidPalindromeProblem.java, src/main/java/leet_code/string/easy/valid_palindrome_2/ValidPalindrome2Problem.java, target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst, target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst, target/surefire-reports/TEST-leet_code.palindrome.tests.ValidPalindromeProblemTest.xml, target/surefire-reports/leet_code.palindrome.tests.ValidPalindromeProblemTest.txt
1. Added Brute Force, Sub Optimal, Optimal
=> leet code: update 680. Valid plaindrome II
